### ISSUE TITLE
Does not compile on Windows

### ISSUE THREAD

**Issue by Mossop** [faradayio/exec-rs#3]
error[E0433]: failed to resolve. Could not find `unix` in `os`
      --> C:\Users\Dave\.cargo\registry\src\github.com-1ecc6299db9ec823\exec-0.3.1\src\lib.rs:19:14
       |
    19 | use std::os::unix::ffi::OsStrExt;
       |              ^^^^ Could not find `unix` in `os`
    
    error[E0599]: no method named `as_bytes` found for type `&std::ffi::OsStr` in the current scope
       --> C:\Users\Dave\.cargo\registry\src\github.com-1ecc6299db9ec823\exec-0.3.1\src\lib.rs:103:49
        |
    103 |         exec_try!(CString::new(program.as_ref().as_bytes()));
        |                                                 ^^^^^^^^
    
    error[E0599]: no method named `as_bytes` found for type `&std::ffi::OsStr` in the current scope
       --> C:\Users\Dave\.cargo\registry\src\github.com-1ecc6299db9ec823\exec-0.3.1\src\lib.rs:105:35
        |
    105 |         CString::new(arg.as_ref().as_bytes())
        |                                   ^^^^^^^^
    
    error: aborting due to 3 previous errors
    
    Some errors occurred: E0433, E0599.
    For more information about an error, try `rustc --explain E0433`.
    error: Could not compile `exec`.

**Comment by Mossop** [comment]
Never mind, I'm told this isn't a thing on Windows anyway.,

**Comment by emk** [comment]
No problem! `exec` is one of those ancient Unix things, essentially a [tail-call optimization](https://en.wikipedia.org/wiki/Tail_call), but for running programs instead of functions.

If anybody figures out how to do something similar on Windows, I'd be happy to accept a PR. But the closest alternative is probably calling `std::process::Command` and waiting for the child process to finish.
